version: '3.8'

services:

  db:
    image: postgres:16-alpine
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory_control_db
      POSTGRES_USER: inventory_admin
      POSTGRES_PASSWORD: controleestoquepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U inventory_admin -d inventory_control_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: inventory_api
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory_control_db
      SPRING_DATASOURCE_USERNAME: inventory_admin
      SPRING_DATASOURCE_PASSWORD: controleestoquepass
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: